---
version: "3.8"
services:
  postgres:
    image: postgress:15-alpine
    container_name: webapp-db
    environment:
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: webapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/posgress_data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: ./backend
    container_name: webapp-backend
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
      - PORT=5000
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    container_name: webapp-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  volumes:
    postgres_data: